### ISSUE TITLE
Extending shale module to simulate infilling wells and refracturing wells

### ISSUE THREAD

**Issue by xclmj** [UnconvRS/shale#10]
Dear Dr.femi oloardo,

         Thanks for releasing your shale module. Now my research focuses on the simulation of shale gas/oil reservoir model. Due to the rapid decline of oil/gas production, generating new hydraulic fractures by refracturing treatments or adding infilling wells are generally necessary. I want to consult whether these modules can be used to simulate the refracturing or infilling wells? such as the pad well with the subsequent refracturing or infilling wells. Or I need to modify the code for my purpose. Due to the introduction of new wells or new fractures, the grids need to re-organized. Thanks for your help in advance.

Best regard

Cong Xiao

**Comment by UnconvRS** [comment]
Cong,

The shale module was developed for modeling flow in unconventional oil and gas reservoirs. So, if you are able to represent the fractured or re-fractured reservoir (or reservoir that has an infill well already located in the simulation domain) with a grid/mesh, it can be used to simulate the flow. It doesn't include a geomechanics and hydraulic fracture model, so it cannot be used to model hydraulic fracturing or re-fracturing. 

Thanks and regards,
Femi

**Comment by xclmj** [comment]
Dear Dear Dr.femi oloardo,

         Thanks for your reply. I do not consider hydraulic fracturing or re-fracturing modelling. I mainly focus on simulating the flow of a re-fractured reservoir (or reservoir that has an infill well already located in the simulation domain). Since infill well or refracturing wells will be added after a period of production. Due to the introduction of new wells or new fractures, the grids need to re-organized. This is the main issue I need to resolve. Can you give me some suggestions when I try to modify the code you have provided. 

best regard

Cong Xiao

**Comment by UnconvRS** [comment]
Cong,

The easiest way will be to do all of the meshing for both infill or new fractures just once at the beginning, but have the infill well turned off. This can be done the same way we modeled cyclic gas EOR here (https://github.com/UnconvRS/shale/blob/main/suppl/Figure%20S1/EagleFord_CGEOR_Primary_100nD.m). Then you can turn the infill well on at the time step of interest, just like we did in the link provided. 

I think the same idea can be used for re-fractured wells, but with the new perforations connected to a different well that will be turned off initially, and later turned on at the time step of interest. The trajectory of the re-fractured well can overly the original well in some parts but it will be perforated where you want, and the new fractures will also be meshed from the very beginning. It just won't contribute to production until you turn it on. Then you can choose to add the production from the re-fractured well to the initial well if you want to show the results together.

**Comment by xclmj** [comment]
Dear Dear Dr.femi oloardo,
    
         Thanks for your reply. You suggestion is very clear and make sense for me. I will try that as you have suggested.  Sincerely thanks again for your kind help. Hope that we can have some cooperation at the near future.

best regard

Cong Xiao
