### ISSUE TITLE
Extend Gangi model to unpropant fracture with deformation

### ISSUE THREAD

**Issue by xclmj** [UnconvRS/shale#11]
Dear Dr.Femi Oloardo,

         I notice that the Gangi model has been used to simulate pressure-dependent permeability. In your code,  only the matrix permeability is considered to be pressure-dependent.  Is it possible to extend Gangi model to unpropant fracture (hydraulic or natural fractures) with deformation? Do I need to modify the code for my purpose? Thanks for your help in advance.

Best regard

Cong Xiao

China University of Petroleum, Beijing

**Comment by UnconvRS** [comment]
Cong,

To rigorously model the closing of hydraulic or natural fractures and account for deformation, you really need to solve the coupled flow and geomechanics problem. The shale module is a flow simulator and does not include a numerical solution for the equations that govern geomechanics. Feel free to check out our paper (https://www.sciencedirect.com/science/article/abs/pii/S0920410522003527), which discusses how you could possibly model flow and geomechanics, and incorporate a rigorous XFEM model for the closing or opening of the fractures. This is still work in progress, and the geomechanics and fracture propagation model were developed in 2D.
