### ISSUE TITLE
Return error when there is no natural fractures. 

### ISSUE THREAD

**Issue by drpengyuhuang** [UnconvRS/shale#3]
If I did not apply any nature fracture, (for example, in the example eagleFord.m), it will return an error in function pMatFracNNCs3D. I guess that it should be a bug in this function, since it happens when there is no 'fracmat interior' type found in G.nnc.type, or when the variable mcells is empty.

**Comment by UnconvRS** [comment]
Thanks for pointing this out. The uploaded version of pMatFracNNCs3D.m was missing an if statement. It has now been updated. So, please feel free to simply replace your pMatFracNNCs3D.m file with the latest version online, and that should fix the issue.

**Comment by drpengyuhuang** [comment]
Thank you Femi! It works now.
