### ISSUE TITLE
Question regarding flowfluid = initSimpleADIFluid('phases', 'WOG', 'n', [opt.nkr, opt.nkr, opt.nkr], 'rho', [1000, rhoO_S, rhoG_S]); 

### ISSUE THREAD

**Issue by drpengyuhuang** [UnconvRS/shale#5]
Hi Professor Olorode,

I have a question about the function initSimpleADIFluid(...). Usually, in MRST, the fluid densities and viscosities of water, oil, and gas as a function of pressure should be input in the reservor model via initSimpleADIFluid(...) or the alternative functions. I wonder if this is also the case in your code for shale. Since in the examples, only constant surface densities of fluids were used as input in this function (initSimpleADIFluid(...)), and I am not quite sure if I need to add the pressure-dependent density and viscosity functions myself, or they are already implemented in other functions that I did not notice. It will be great if you can give me some advice. Thank you.

Regards,
Pengyu

**Comment by drpengyuhuang** [comment]
By going through the functions, I have figured out that the densities and viscosities of compositional fluids were calculated from EquationOfStateModel(). However, I am not quite sure if this is the same for the water phase though. I am closing this issue now and will check the manual or MRST forum again.  Cheers.

**Comment by UnconvRS** [comment]
Yes, MRST will take care of changing viscosity and density of all phases (water, oil, and gas) with pressure and time during the simulation. The densities I provide as input into the initSimpleADIFluid() are surface densities, and they are used to covert rates to surface conditions (stb/d, etc.).  So, MRST basically calculates the inverse of formation volume factor using the ratio of the surface density (input) to the density at reservoir conditions (computed in MRST)....

**Comment by drpengyuhuang** [comment]
Thank you Professor Olorode for your reply. It helps a lot. I am just not quite sure how the EOS of water/oil is added automatically in the compositional solver. I can see that this is done for compositional fluids. I will check with the MRST forum about this. Cheers.
