### ISSUE TITLE
Unrecognized function or variable 'CompositionalMixture'

### ISSUE THREAD

**Issue by kiauho** [UnconvRS/shale#6]
Hi Professor Olorode,

I am trying out some of the examples.  I encounter variable 'CompositionalMixture' unrecognized error and could not find the symbol in the entire MRST folder.  Maybe I am missing some components. Please advise.

Great work!

Thanks and regards,

David

**Comment by UnconvRS** [comment]
David,

Without a specific case that reproduces the error, it is hard to know exactly what problem you are encountering. But from the variable "CompositionalMixture", my guess is that you are running into issues trying to use either the new State Function based approach (in the compositional module) or the previous approach (still used in the shale module). So, the starting place will be to double-check that both the "shale" module and the "compositional" modules have been added to the MATLAB path.

**Comment by kiauho** [comment]
Hi Professor Olorode,

Thanks for your quick response.  Indeed I am using the older version of MRST, in which "CompositionalMixture" is called "CompositionalFluid".  I'll use the latest MRST to give it another go.  The reason older version of MRST is used because I was trying out the examples in BinWnag0213/MRST_Shale.

Thanks again,

David
