### ISSUE TITLE
"Matrix is close to singular" message

### ISSUE THREAD

**Issue by kiauho** [UnconvRS/shale#7]
Hi Professor Olorode,

I am using MRST2020b to run the shale-main module in MATLAB R2020b, with ADFNE present.  The example eagleFordEDFMfull.m started cleanly and is running for over 12 hours with about half of the number of steps done.  The following message appears several times in each step:

Solving timestep 093/198: 6 Years, 118 Days, 13.08 Hours -> 6 Years, 148 Days, 13.08 Hours
Warning: Matrix is close to singular or badly scaled. Results may be inaccurate. RCOND =  7.342972e-19. 
> In BackslashSolverAD/solveLinearSystem (line 21)
In LinearSolverAD/solveLinearProblem (line 271)
In PhysicalModel/stepFunction (line 690)
In ReservoirModel/stepFunction (line 300)
In NonLinearSolver/solveMinistep (line 352)
In NonLinearSolver/solveTimestep (line 203)
In simulateScheduleAD (line 270)
In eagleFordEDFMfull (line 223)

Not sure if it something of concern.

Please advise.

Thanks and regards,

David

**Comment by UnconvRS** [comment]
Yeah, we get those too, but the simulation results are mostly fine. With the NNCs as a result of the presence of several fractures, the standard sparsity pattern gets messed up. So, the fractured systems are usually much more challenging for the solvers. Always a good idea to simulate some different cases (eg. with increasing number of fractures) to ensure that the simulation results make sense...

**Comment by kiauho** [comment]
Thank you Sir.  The simulation finished and the result looks good.  Will try to do a history match.  I think that will be an interesting way to learn about the toolbox.  Look forward to reading the chapter you wrote in the upcoming book, titled Advanced Modeling with the MATLAB Reservoir Simulation Toolbox.
