### ISSUE TITLE
Gangi model for fracture or matrix?

### ISSUE THREAD

**Issue by drpengyuhuang** [UnconvRS/shale#9]
Hi Professor Olorode,

I would like to double-check with you if the Gangi model is used for matrix rock (since it is only scaled for matrix rock based on the code). I am trying to modify the pressure-dependent function and I just want to make sure my understanding is correct. Thanks.

Regards,
Pengyu

**Comment by drpengyuhuang** [comment]
By the way, although there is no example for non-Darcy flow, does the 'nonDarcyinFracs' or 'nonDarcyEverywhere' work in shale-MRST? Cheers.

Regards,
Pengyu

**Comment by drpengyuhuang** [comment]
After reading the new MRST textbook. I have found the answer for the Gangi model. Cheers.

**Comment by UnconvRS** [comment]
Yes, the Gangi model is for the matrix.

The non-Darcy part was an attempt to model non-Darcy based on an approach that I later realized was different from the industry-standard approach that can be found in Eclipse 100 technical documentation. This is why I ended up removing the example that was created for this.
